version: '3'
services:
  app:
    build: .
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
#      - 127.0.0.1:15672:15672
    volumes:
      - .:/app
#      - ./conf/php.ini:/opt/docker/etc/php/php.ini
    working_dir: /app/
    environment:
      - APP_ENV=local
      - VIRTUAL_HOST=http://iot.local
      - LOG_STDERR=/marekerror.log
    links:
      - rabbitmq
      - mongodb

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672

  mongodb:
    image: mongo
    volumes:
      - ./db/:/data/db
    ports:
      - 127.0.0.1:27017:27017


